### ISSUE TITLE
im sorry im a complete noob

### ISSUE THREAD

**Issue by Neospell** [davidborzek/streamdeck-foobar2000#2]
how do i install this there is nothing showing how

**Comment by davidborzek** [comment]
Hey,
first make sure you have foobar installed with the [beefweb](https://github.com/hyperblast/beefweb) plugin.
Then just download the latest [release](https://github.com/davidborzek/streamdeck-foobar2000/releases/download/v1.4/com.davidborzek.foobar2000.streamDeckPlugin). Run the file and the Elgato Stream Deck App will ask you to install the plugin.
