### ISSUE TITLE
Play / Pause distinct buttons

### ISSUE THREAD

**Issue by Emulga** [davidborzek/streamdeck-foobar2000#3]
Hi and first thank you for this great plugin.

Request : I would like to have the ability to have a PLAY button separated from the PAUSE button. Or options on the current Play/Pause button to set a behavior.

Context : I'm a streamer using different scenes in the OBS software. Chances are that you know a little bit about streaming as the Streamdeck was first developed for streamers using OBS mainly. Thing is that I've got some scenes where I want to have music playing and other scenes like my introduction video, my trailer video when I get hosted, my gaming scene, etc where I don't want any background music from foobar2000.

How to do that : With a Multi Action in Stream Deck button including "scene change" + "your plugin (play or pause)".

Problem : Currently the play/pause button will play or pause the music no matter from which scene I'm coming from.

Having "play" for scenes I need music would play no matter if I'm coming from a scene with or without music.
Having "pause" for scences I don't want music would pause no matter if I'm coming from a scene with or without music.

I hope I've explained this correctly. I'm a full time streamer and this maybe sounds useless to you but it would really help concentrate on what's important while streaming. I can pay with Paypal for the development. I understand that this would take some time of dev on your end but I do really need this. I would much more like to see this implemented in the official Github than paying someone to fork your project and then one day it'll break.

Thanks a lot again and I do really hope you'll like the idea and implement it!

*Also I'm aware of the VLC remote plugin that does exactly this but I don't want to use VLC as there's no fade in/out option upon play/pause.

**Comment by davidborzek** [comment]
Hello,

Thank you for the request. If I understand you right, you just want to have separated play and pause buttons?

**Comment by Emulga** [comment]
Hi, 

I guess it would have been much simpler if I said that!

Yes, separated play and pause buttons!

Thanks a lot 💯

**Comment by davidborzek** [comment]
#4

**Comment by davidborzek** [comment]
#
